### ISSUE TITLE
Thanks, compression, tls setup?

### ISSUE THREAD

**Issue by paradisaeidae** [Trust-Anchor-Group/ComSim#1]
Thanks for putting this up Peter!
I'm already an xmpp fanboy.
json is poorman's xml.
Though some might ask what about the overhead metrics?
Is there one TLS session setup per message?
Is there any compression factored in anywhere?
Compression really only useful with large messages presumably.
Websockets are not just in the browsers, so is this a significant tool?

A large pod of Dolphins swam by on my walk to coffee this morning.
Such a welcome moment!
Safety to you all there!

**Comment by PeterWaher** [comment]
Hello

Connections in ComSim are managed by actors. These can be connected during the entire simulation, or part of it, defined by activity actions. The examples allow actors to be connected in sessions spanning the entire simulation. There is no compression used in these examples as well. Some examples use only TCP socket connections, others use WebSockets and/or BOSH. Simulator is agnostic to this however, so if you wanted to simulate shorter sessions, or sessions using compressed communication, you are free to do so. ComSim is just a simulation engine, allowing for actors, actions, events, etc., to be defined in extensible modules.

Best regards,
Peter
